name: Windows CI
on: [push]

jobs:
  test:
    strategy:
      matrix:
        include:
          - python_version: "3.9"
            numpy_version: numpy
            tf_version: tensorflow
            nengo_version: nengo[tests]
          - python_version: "3.10"
            numpy_version: numpy
            tf_version: tensorflow --pre
            nengo_version: git+https://github.com/nengo/nengo.git#egg=nengo[tests]
          - python_version: "3.7"
            numpy_version: numpy==1.16.0
            tf_version: tensorflow==2.2.0
            nengo_version: nengo[tests]==3.0.0
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install pip setuptools --upgrade
          pip install ${{ matrix.numpy_version }} ${{ matrix.tf_version }} ${{ matrix.nengo_version }}
          pip install -e .[tests]
          pip freeze
      - name: Run tests
        run: |
          pytest -v -n 2 --color=yes --durations 20 nengo_dl
          pytest -v -n 2 --color=yes --durations 20 --pyargs nengo
